FROM ubuntu:21.10

RUN cd /tmp && mkdir java
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN  apt-get update \
  && apt-get install nano

RUN wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/otn-pub/java/jdk/16.0.2%2B7/d4a915d82b4c4fbb9bde534da945d746/jdk-16.0.2_linux-x64_bin.tar.gz -P /tmp/java/
RUN tar xvzf /tmp/java/jdk-16.0.2_linux-x64_bin.tar.gz -C /tmp/java
ARG JAVA_HOME=/tmp/java/jdk-16.0.2
ENV JAVA_HOME=${JAVA_HOME}
ENV PATH="${JAVA_HOME}/bin:${PATH}"

## zoo keeper
RUN wget https://downloads.apache.org/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz -P /tmp/
RUN tar -zxf /tmp/apache-zookeeper-3.7.0-bin.tar.gz -C /tmp/
RUN mv /tmp/apache-zookeeper-3.7.0-bin /tmp/zookeeper
RUN mkdir -p /var/lib/zookeeper
COPY zoo.cfg /tmp/zookeeper/conf/
COPY myid /var/lib/zookeeper

COPY app-entrypoint.sh /tmp/
ENTRYPOINT ["/tmp/app-entrypoint.sh"]